//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mikroklimat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int id { get; set; }
        public string path { get; set; }
        public Nullable<short> project_id { get; set; }
        public string small_img_path { get; set; }
    
        public virtual project project { get; set; }
    }
}
